### ISSUE TITLE
bug: deploying account to shard 0 fails as it is marked as master shard.

### ISSUE THREAD

**Issue by bajpai244** [NilFoundation/nil.js#106] opened 2024-07-24 07:02 UTC
In `assertIsValidShard`, we have a check [here](https://github.com/NilFoundation/nil.js/blob/d919754dce76a2a518af36874e55e3272cf67602/src/utils/assert.ts#L116), making sure shard is not the master shard.

But as of devnet there seems to be no master shard, and since the constant for the master shard is assigned `0`, it makes deployment of wallet on shard 0, not possible!

**Comment by KlonD90** [comment] 2024-07-24 08:54
That's correct for now. It could be changed later. We have some ideas about how to use it. But don't have enough consensus yet.

**Comment by ukorvl** [comment] 2024-07-25 10:31
Closing it for now, cz actually everything is working like it was intended. When in the future we will need to allow to communicate with 0 shard, we will return to that.

**Closed by ukorvl** 2024-07-25 10:31 UTC
